apiVersion: v1
kind: Service
metadata:
  name: openskull-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: openskull-api
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: openskull-api
  type: ClusterIP