name: API Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - .github/workflows/api-dotnet-build-and-test.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - .github/workflows/api-dotnet-build-and-test.yml

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./api/OpenSkull.Api
      run: dotnet restore
    - name: Build
      working-directory: ./api/OpenSkull.Api
      run: dotnet build --no-restore
    - name: Restore dependencies
      working-directory: ./api/OpenSkull.Api.Tests
      run: dotnet restore
    - name: Build
      working-directory: ./api/OpenSkull.Api.Tests
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./api/OpenSkull.Api.Tests
      run: dotnet test --no-build --verbosity normal
